### PR TITLE
state update in Struct fix

### PR DESCRIPTION
**Pull request by Coobaha**
@gcanti with 0.5.2 Struct state update was ignored in react world.
I fix this with kind check like in List with this PR.

### CODE REVIEW

**Comment by gcanti** [comment]
Hi, this is intentional: in a struct `setState` (and then a complete re-rendering) shouldn't be required.
What kind of issues you experimented? Maybe I've overlooked something?

**Comment by Coobaha** [comment]
transformers of struct fields are ignored without state change via setState

**Comment by Coobaha** [comment]
example:
```es6
export let PaymentCardStruct = t.struct({
  pan        : t.subtype(t.Str, luhnChk, 'lun pan'),
  holder     : t.Str,
  validMonth : t.union([t.Str, t.Num]),
  validYear  : t.union([t.Str, t.Num]),
  cvv        : t.subtype(t.Str, (value) => {
    value = value.replace(/\D/g, '');
    return value.length >= 3 && value.length <= 4;
  })
}, 'PaymentCard');

export let PaymentCardOptions = {
  fields : {
    pan        : {
      transformer : {
        format : =>,
        parse  : =>
      }
    },
    cvv        : {
      label       : 'CVV',
      transformer : {
        format : =>
        parse  : =>
      }
    },
    validMonth : {
      factory : NumberInRange,
      min     : 1,
      max     : 12
    },
    validYear  : {
      factory : NumberInRange,
      min     : 15,
      max     : 99
    }
  }
};
```
This setup works with 0.5.1
and not working in 0.5.2 with setState  (with t.union swapped to t.Str)

**Comment by gcanti** [comment]
I'm trying to replicate the problem but your code snippet doesn't work, could you please provide a minimal example which I can use to verify the issue?

**Comment by Coobaha** [comment]
@gcanti sorry for late answer, did not see notification about your reply.
I refactored my component and problem is gone, pure render was stoping update.

**Pull request closed without merging**
