### PR TITLE
Add missing line of code to first example

### PR DESCRIPTION
**Pull request by KyleAMathews**

### CODE REVIEW

**Comment by gcanti** [comment]
Having someone else who double-checks this huge refactoring is very helpful, thanks!

**Comment by KyleAMathews** [comment]
:) working on a new form-heavy feature right now with the 1.4 branch!

**Comment by KyleAMathews** [comment]
(though distracted by the all the cool announcements coming out of ReactConf)

**Comment by gcanti** [comment]
> working on a new form-heavy feature right now with the 0.4 branch!

Great! Let me know if you have issues, I'll try to help you out

> though distracted...

Yeah ... I should prepare my dinner, but I can't stop watching twitter :)
I'm happy to have invested in React

**Pull request merged**
