### PR TITLE
Fix isNumeric check in `numberTransformer`, fix #380

### LINKED ISSUE #380: Bug in numberTransformer
### Version

- tcomb-form v0.9.13
- react v0.15.4

### Expected behaviour

Empty `Textbox` with `Number` type should return `null` after validation even if source of library minified by UglifyJS.

### Actual behaviour

Empty `Textbox` with `Number` type returns `NaN` after validation.

### Steps to reproduce

1. Minify project by UglifyJS
2. Call `validate()` on `Textbox` instance and inspect returned result. Actual value will be reported as `NaN`

### Details

Just found weird issue with `numberTransformer` that occurred after library compression by UglifyJS. Empty `Textbox` value reported as `NaN` after `validate` call.

It caused by incorrect [`isNumeric`](https://github.com/gcanti/tcomb-form/blob/master/src/components.js#L268) detection logic in `parseNumber` function used in `numberTransformer`. 
For empty string `parseFloat` will return `NaN` that can't be correctly compared with zero. Result always will be `false` regardless of operator `<` or `>`. 
After minification (with `unsafe_comps` option) 
```
function parseNumber(value) {
  const n = parseFloat(value)
  const isNumeric = (value - n + 1) >= 0
  return isNumeric ? n : toNull(value)
}
```
will became
```
function c(e) {
  var t = parseFloat(e);
  return 0 > e - t + 1 ? l(e) : t
}
```  
So compare operator has changed but result still the same – `false` and finally `NaN` is returned.
Hope my explanation is clear.
So it will be great if deeply minified `tcomb-form` will work correctly.

### PR DESCRIPTION
**Pull request by gbiryukov**
See #380 for more details

### CODE REVIEW

**Comment by gcanti** [comment]
> So it will be great if deeply minified tcomb-form will work correctly

I agree, the new version behaves differently though

```js
// old
function isNumeric(value) {
  const n = parseFloat(value)
  return (value - n + 1) >= 0
}

// new
function isNumeric2(value) {
  const n = parseFloat(value)
  return typeof n === 'number' && isFinite(n)
}

console.log(isNumeric('a')) // false
console.log(isNumeric('1')) // true
console.log(isNumeric('1.2')) // true
console.log(isNumeric('1.2a')) // false
console.log(isNumeric('1.a2')) // false
console.log(isNumeric('1a2')) // false

console.log(isNumeric2('a')) // false
console.log(isNumeric2('1')) // true
console.log(isNumeric2('1.2')) // true
console.log(isNumeric2('1.2a')) // true (!)
console.log(isNumeric2('1.a2')) // true (!)
console.log(isNumeric2('1a2')) // true (!)
```

**Comment by gbiryukov** [comment]
Yep, by bad! I've added tests to ensure that changes will be completely compatible with current implementation and updated the fix

**Comment by gcanti** [comment]
Looks good, thanks for the tests. I'll release a patch asap

**Comment by gcanti** [comment]
Patch released

**Comment by gbiryukov** [comment]
👍

**Pull request merged**
